project:
  type: website

website:
  page-navigation: true
  title: "Virtual Store Feasibility Report"
  sidebar:
    pinned: true
    align: center
    logo: graphics/nasa-logo.png
    contents:
      - href: index.qmd
        text: Home
      - href: executive_summary.qmd
        text: Executive Summary
      - section: Technical Aspects
        contents:
          - href: technical-overview.qmd
            text: Technical Overview of Virtual Stores
          - href: nasa-applications.qmd
            text: Applications of Virtual Stores at NASA
          - href: nasa-ecosystem.qmd
            text: Virtual Stores within the NASA Ecosystem
      - section: Guidance
        contents:
          - href: limitations.qmd
            text: Known Limitations
          - href: governance.qmd
            text: Governance
      - href: recommendations.qmd
        text: Best Practices + Recommendations
      - href: onboarding.qmd
        text: Onboarding Guide
      - href: examples.qmd
        text: Examples
      - href: contributing.qmd
        text: Contributing
      - href: resources.qmd
        text: Resources, References and Presentations        

format:
  html:
    theme: nasa.scss
    toc: true
