---
title: "Virtual Stores and the NASA Ecosystem"
subtitle: "How Virtual Stores integrate with the rest of the NASA Data System"
---

There are a number of components to consider when envisioning virtual stores and their place in the broad NASA data ecosystem.

Virtual stores provide a uniform interface to archival data through the Zarr data model and specification. However, to access and visualize this data, the ecosystem needs to adapt to integrate the Zarr data model and specification. While xarray and zarr-python provide powerful tools for working with this data, a number of existing powerful tools at NASA need to be considered to support NASA users.

## Integration with EGIS

[ADDME: @abarciauskas-bgse]

## Integration with Harmony

[ADDME: @owenlittlejohns]

## Discovery and integration with CMR

[ADDME]

## Integration with earthaccess

[`earthaccess`](https://earthaccess.readthedocs.io/en/latest/) currently supports data virtualization (via VirtualiZarr) that can be used to streamline the creation and access of virtual stores.
The current implementation allows end-users and data providers to generate a virtual store at scale with a **single line of code**. Scale is delivered using the parallel executors API from Virtualizarr which utilizes a Dask cluster or Lithops if configured.

```python
import earthaccess as ea

granules = ea.search_data(**params)

vds = ea.virtualize(granules, **virtualizarr_options)

# then we can persist the vds into kerchunk or icechunk
vds.virtualize.to_kerchunk(*args)
# or 
vds.virtualize.to_icechunk(*args)

```

This approach allows users to easily create virtual stores from their search results, and then persist those virtual stores without having to manually configure anything (I/O drivers and authentication).
By using CMR search results earthaccess enables creation of tailored virtual stores. Virtual stores can be created "on the fly" using only the subset of files that meet certain criteria. Use cases include creating seasonal and regional datasets.


Once a virtual store is created, updating it will also be streamlined with `earthaccess`. Once the store's metadata is listed in a CMR collection level record or a new UMM association, 
then we will be able to use `earthaccess` to update the virtual store with new granules that get added to the collection, or even remove granules that get deleted from the collection. 
This would allow users to maintain up-to-date virtual stores without having to manually track changes to the underlying data.

```python

colection = ea.search_datasets(
  short_name="SPL4SMGP"
)[0]

icechunk_store = ea.open_virtual_store(colection, name="yearly_store")

# then we can use a CMR search to look for new granules with created_at
params = {
  "created_at": <latest timestep of icechunk store + 1 timestep>
}
new_granules = ea.search_data(**params)
new_vds = ea.virtualize(new_granules, **vz_options)

# append the new to the current store
new_vds.virtualize.to_icechunk(icechunk_store, append_dim="time")
```

The same way, we can use `icechunk_store` to open it using xarray and visualize it with tools like `hvplot` or `matplotlib`.

```python
ds = xr.open_zarr(icechunk_store, consolidated=False, zarr_format=3)
```
