---
title: "Technical Features"
subtitle: Additional information on technical features and their maturity levels
---

# Mature Support

# Developing Support

## Non-uniform grids

Some NASA collections present additional complexity due having varying compression schemes and chunk grids across a logical array (usually across granules). At this point in time, Zarr assumes consistent chunk shape and compression across the entire array. 

However, support for both varying chunk shapes and compression schemes is in active development and should be available by summer 2026.

## Non-cubable data

COMING SOON

# No plans for support

## Unsupported data formats

Data format support is limited to formats with VirtualiZarr parser implementations.

Parsers maintained by VirtualiZarr include:

* [HDFParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/hdf/hdf.py)
* [Kerchunk (Parquet or JSON)](https://github.com/zarr-developers/VirtualiZarr/tree/main/virtualizarr/parsers/kerchunk)
* [DMRPPParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/dmrpp.py)
* [FITSParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/fits.py)
* [NetCDF3Parser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/netcdf3.py)
* [ZarrParser](https://github.com/zarr-developers/VirtualiZarr/blob/main/virtualizarr/parsers/zarr.py)
  
Parsers maintained outside of VirtualiZarr include:

* [virtual-tiff](https://virtual-tiff.readthedocs.io/en/latest/)
* [hrrr-parser](https://github.com/virtual-zarr/hrrr-parser)

Custom parsers for additional formats can be implemented using the VirtualiZarr [CustomParsers](https://virtualizarr.readthedocs.io/en/stable/custom_parsers.html) guide.